### ISSUE TITLE
SCSS Lint has timed out after waiting for 10000 ms

### ISSUE THREAD

**Issue by amitmtrn** [chimo/brackets-scss-lint#1]
I'm getting this error when tring to lint scss file.

`SCSS Lint has timed out after waiting for 10000 ms`

**Comment by chimo** [comment]
On which platform are you?

On Linux (and possibly Mac), I seem to recall Brackets/Node not inheriting the user's PATH environment variable and using the system's default instead. Which caused problems when trying to locate the scss-lint Ruby gem if installed in the user's /home directory.

**Comment by amitmtrn** [comment]
I'm using windows 7 64 bit

**Comment by amitmtrn** [comment]
ok, I didn't know I have to install 'gem install scss-lint'
now it's work.
