### ISSUE TITLE
Scss lint no longer works

### ISSUE THREAD

**Issue by the-Dean** [chimo/brackets-scss-lint#11]
This does not work anymore for me. I've installed the latest version, but I get this error
SCSS Lint terminated with error: Unknown error, and I'm on forked version of brackets, but I also tested in on version 1.5

**Comment by chimo** [comment]
Just to make sure, did you also install the [scss-lint Ruby gem](https://github.com/causes/scss-lint) (in addition to this brackets-scss-lint extension) ?

Which OS are you running?

Did you install the brackets-scss-lint extension from the Brackets Extension Manager or from this Github repository?
