### ISSUE TITLE
Can't find "scsslint.gemDir" in Brackets Preference File

### ISSUE THREAD

**Issue by ksharifbd** [chimo/brackets-scss-lint#12]
I am using 

Release 1.5 build 1.5.0-16538 (release cf9cf4698) 
build timestamp: Wed Oct 14 2015 04:40:12 GMT-0700

**Comment by chimo** [comment]
Hi,
  The "scsslint.*" settings aren't present in the preference file by default.
If you need them, you can add them to the file and they should get picked-up by the plugin after reloading Brackets.

Let me know if that helps.

**Comment by ksharifbd** [comment]
This is my brackets.json file. I am using OSX Yosemite. I got the gem directory by running "gem environment". I think I am making mistakes in defining directory.
<img width="613" alt="screen shot 2015-12-23 at 11 57 15 am" src="https://cloud.githubusercontent.com/assets/7776002/11971766/70d3bf36-a96c-11e5-88b7-35c4af945a13.png">

**Comment by chimo** [comment]
The way I find the scss-lint path is with `which scss-lint`

For me, it outputs `/home/chimo/.gem/ruby/2.2.0/bin/scss-lint`
Then I use the following path in my Brackets preference file: `/home/chimo/.gem/ruby/2.2.0/bin/`

Also, make sure you're running v0.3.0 of the brackets-scss-lint extension (I just pushed an update now).

Let me know if that works

**Comment by ksharifbd** [comment]
Just've pulled the updates and got the path using ```which scss-lint``` command. In my case, it ouputs ```/usr/local/bin/scss-lint```

It's working perfectly. Thanks a lot.

**Comment by chimo** [comment]
Cheers!
