### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by depiction** [chimo/brackets-scss-lint#14]
Brackets shows the following error in the SCSS Lint panel:

SCSS Lint terminated with error: Error: Command failed: scss-lint -f JSON -c /path/.scss-lint.yml "/path/main.scss" /bin/sh: scss-lint: command not found	

If I type the same command into Terminal, it works, so I know scss-lint is installed.

**Comment by chimo** [comment]
Can you run `which scss-lint` in Terminal, and add the path to the "scss-lint" binary in your brackets.json file like so:

`"scsslint.gemDir": "/path/to/scss-lint/bin/"`

**Comment by depiction** [comment]
That worked; thanks.
