### ISSUE TITLE
Remote Config File

### ISSUE THREAD

**Issue by red2678** [chimo/brackets-scss-lint#3]
Hi, we share our config files up from a central sever. How could I specify that?

Thanks!!

**Comment by chimo** [comment]
Good question.

Can you provide more details on how those files can be accessed in your situation?
e.g.: remote drive mounted locally, over HTTP/FTP, Dropbox, etc?

**Comment by red2678** [comment]
@chimo Thanks for the response. 

We currently serve them from a local IIS server (via HTTP) on our internal network.

**Comment by red2678** [comment]
Hi @chimo any word on this? Thanks so much!

**Comment by chimo** [comment]
Sorry! I got side-tracked...

When you get a chance, can you download [this zip](https://github.com/chimo/brackets-scss-lint/archive/remote.zip) from the [experimental branch](https://github.com/chimo/brackets-scss-lint/tree/remote)?

Close brackets, remove the current scss-lint extension, extract the zip file in your extension folder, open brackets.

Right now the way it should works is:
1. Checks if .scss-lint.remote.yml exists
2. If so, reads the file which should only contain a URL to the real config file.
3. Copies the content of the remote file in .scss-lint.yml
4. Calls the linter with .scss-lint.yml as the config file

If .scss-lint.remote.yml doesn't exist in step 1, it'll fallback to .scss-lint.yml
If .scss-lint.yml doesn't exist, it'll call the linter without a config file.

Let me know how this initial implementation works out
