### ISSUE TITLE
SCSS Lint Problem: "Unknown error"

### ISSUE THREAD

**Issue by maelfrize** [chimo/brackets-scss-lint#4]
I am getting the same SCSS Lint Problem in every SCSS file: "SCSS Lint terminated with error: Unknown error	".

I am running Brackets Release 1.2 build 1.2.0-15697 (release 8f82e2a97) on Mac.

Any ideas why this happens?

**Comment by chimo** [comment]
Hi!
I updated the extension just now.
New error codes were added to scss-lint and the extension wasn't handling them:

> 80: No files matched by specified glob patterns
> 81: This file is filtered by exclusions

Can you try updating?
Let me know if it fixes your issue or not.

**Comment by maelfrize** [comment]
Hey,

I'm still getting the same error inside Brackets.

Also, inside Chrome Dev Tools it says "[CodeInspection] Provider SCSS Lint (async) failed: Unknown errorextensions/default/DebugCommands/ErrorNotification.js:125 window.console.error"

**Comment by chimo** [comment]
Can you provide which version of Ruby and scss-lint you're running?

**Comment by maelfrize** [comment]
I have updated scss-lint right after writing my last comment, and now it work’s. I'm not sure what version I had before.

Sorry, I should have done that before submitting this issue.

Thanks anyway for your quick support. Great plugin!

**Comment by chimo** [comment]
Cheers! :)
