### ISSUE TITLE
Brackets scss_lint says "SCSS Lint terminated with error: Input file did not exist or was not readable" when I put a config file in the folder.

### ISSUE THREAD

**Issue by jithinvmohan** [chimo/brackets-scss-lint#8]
SCSS Link Brackets extension works if I do not put the config file. But when I add the config file .scss-lint.yml it gives the error "SCSS Lint terminated with error: Input file did not exist or was not readable".

The contents of the config file is the default one available at https://raw.githubusercontent.com/brigade/scss-lint/master/config/default.yml.

![image](https://cloud.githubusercontent.com/assets/919955/9006169/c27d9e48-37a1-11e5-91af-ed0ab96daee2.png)

Brackets: Release 1.4 build 1.4.0-16380
scss_link: 0.40.1
OS: Windows 7

**Comment by chimo** [comment]
Using the same software versions and config file, I'm not getting that error on my end.
Can you check if you get that error on a very simple SCSS file:
```
p {
  margin: 0;
}
```

If the error appears with that simple file, can you try linting from the `scss-lint` command-line tool and see what happens:
```scss-lint -c .scss-lint.yml simple-file.scss```

**Comment by jithinvmohan** [comment]
Sorry I was on vacation and couldn't reply earlier.
I check now and the same machine seem to work as expected like our other machines. Not able to reproduce the issue at the moment.

**Comment by chimo** [comment]
Glad to hear it's working.
Feel free to re-open if you run into problems
