### ISSUE TITLE
SCSS Lint terminated with error: Unknown error

### ISSUE THREAD

**Issue by kmturley** [chimo/brackets-scss-lint#9]
I'm getting this error on every scss file i'm using:

    SCSS Lint terminated with error: Unknown error

I'm using Brackets:
Release 1.5 build 1.5.0-16538 (release cf9cf4698) 
build timestamp: Wed Oct 14 2015 04:40:12 GMT-0700

**Comment by chimo** [comment]
Hi,
Which OS are you running?

**Comment by kmturley** [comment]
<img width="509" alt="screen shot 2015-11-03 at 10 16 32 am" src="https://cloud.githubusercontent.com/assets/1710493/10911692/fea3c4e4-8213-11e5-9691-766df1e4929c.png">

npm 2.10.1
node v0.12.4

**Comment by chimo** [comment]
Can you try the version on master ( https://github.com/chimo/brackets-scss-lint/archive/master.zip )  and make sure "scsslint.gemDir" points to the correct directory where the scss-lint gem is installed  (  https://github.com/chimo/brackets-scss-lint#brackets-scss-lint-configuration )

**Comment by kmturley** [comment]
ah that's the problem, didn't have the Ruby gem! This command fixed it for me:

    sudo gem install scss_lint

Thanks for your quick response!

**Comment by chimo** [comment]
:+1:
